### ISSUE TITLE
LABEL BlockType?

### ISSUE THREAD

**Issue by ghost** [PenguinMod/PenguinMod-Vm#15]
Now I am actively studying the components of Scratch and its modifications. As I understand it, `BlockType.LABEL` was only added to PinguinMod and I want to know how it works from the inside. In total, I found only 2 commits related to this type ([first](https://github.com/PenguinMod/PenguinMod-Vm/commit/7ba720035d18a0067e8c9fcef8f1311e93eb4c02#diff-ff09701ab5ee2d3a147e1bbb65fdc947ee5c97a8c2c4794f9d952d53b18ebf9e), [second](https://github.com/PenguinMod/PenguinMod-Vm/commit/2b1e3679a5ff714b9e3c15197b3e0121c4641902#diff-ff09701ab5ee2d3a147e1bbb65fdc947ee5c97a8c2c4794f9d952d53b18ebf9e)) and, I wonder if there were any more commits to add it?

**Comment by ghost** [comment]
Is this the right place for questions? It's just my first question here...

**Comment by Ianyourgod** [comment]
I suggest using the discord for asking questions

**Comment by RedMan13** [comment]
> Now I am actively studying the components of Scratch and its modifications. As I understand it, `BlockType.LABEL` was only added to PinguinMod and I want to know how it works from the inside. In total, I found only 2 commits related to this type ([first](https://github.com/PenguinMod/PenguinMod-Vm/commit/7ba720035d18a0067e8c9fcef8f1311e93eb4c02#diff-ff09701ab5ee2d3a147e1bbb65fdc947ee5c97a8c2c4794f9d952d53b18ebf9e), [second](https://github.com/PenguinMod/PenguinMod-Vm/commit/2b1e3679a5ff714b9e3c15197b3e0121c4641902#diff-ff09701ab5ee2d3a147e1bbb65fdc947ee5c97a8c2c4794f9d952d53b18ebf9e)) and, I wonder if there were any more commits to add it?

turbowarp now has labels to

**Comment by RedMan13** [comment]
> Now I am actively studying the components of Scratch and its modifications. As I understand it, `BlockType.LABEL` was only added to PinguinMod and I want to know how it works from the inside. In total, I found only 2 commits related to this type ([first](https://github.com/PenguinMod/PenguinMod-Vm/commit/7ba720035d18a0067e8c9fcef8f1311e93eb4c02#diff-ff09701ab5ee2d3a147e1bbb65fdc947ee5c97a8c2c4794f9d952d53b18ebf9e), [second](https://github.com/PenguinMod/PenguinMod-Vm/commit/2b1e3679a5ff714b9e3c15197b3e0121c4641902#diff-ff09701ab5ee2d3a147e1bbb65fdc947ee5c97a8c2c4794f9d952d53b18ebf9e)) and, I wonder if there were any more commits to add it?

since you arnt in the discord im going to mention it here

see [here](https://github.com/PenguinMod/penguinmod.github.io/blob/develop/src/containers/blocks.jsx#L458) for how blocks get defined
see [here](https://github.com/PenguinMod/PenguinMod-Vm/blob/develop/src/engine/runtime.js#L1695) for how the block xml list is built into a full xml element to be used [here](https://github.com/PenguinMod/penguinmod.github.io/blob/develop/src/containers/blocks.jsx#L383)
and as you kinda already mentioned, the xml for the label is generated [here](https://github.com/PenguinMod/PenguinMod-Vm/blob/develop/src/engine/runtime.js#L1506) which is called by [this function](https://github.com/PenguinMod/PenguinMod-Vm/blob/develop/src/engine/runtime.js#L1506) which is called by [this](https://github.com/PenguinMod/PenguinMod-Vm/blob/develop/src/engine/runtime.js#L1118)

**Comment by ghost** [comment]
@RedMan13 Yes, I've already figured it out (I was one of the people who added the labels to TurboWarp), but thanks anyway for explaining everything in a more structured way. I just forgot to close this issue, sorry.

But by the way, since you mentioned Discord: I tried to join him to ask a few questions, but when I try to log on to the server, I am immediately thrown out of it (I click accept the invitation, and then I see the server literally for half a second, and it is removed from the list). I noticed that the server itself shows a message that I need to perform a few more steps in order to use it, but I can't even read these steps. I also tried to register in PinguinMod via ScratchAuth, maybe it will help somehow, but I can't even do that, since the servers are not working, and I'm not the only one complaining about it. Do you know what I did wrong? I would be very grateful if you could help me.

**Comment by RedMan13** [comment]
> @RedMan13 Yes, I've already figured it out (I was one of the people who added the labels to TurboWarp), but thanks anyway for explaining everything in a more structured way. I just forgot to close this issue, sorry.
> 
> But by the way, since you mentioned Discord: I tried to join him to ask a few questions, but when I try to log on to the server, I am immediately thrown out of it (I click accept the invitation, and then I see the server literally for half a second, and it is removed from the list). I noticed that the server itself shows a message that I need to perform a few more steps in order to use it, but I can't even read these steps. I also tried to register in PinguinMod via ScratchAuth, maybe it will help somehow, but I can't even do that, since the servers are not working, and I'm not the only one complaining about it. Do you know what I did wrong? I would be very grateful if you could help me.

yeah wick bot is refusing to let you join because the account is to young 
![noooooooooooo](https://media.discordapp.net/attachments/1038251742439149661/1089319495878840330/ezgif.com-optimize_1.gif)

**Comment by True-Fantom** [comment]
Nooo! I have an account for 20 years how could this happen!

**Comment by RedMan13** [comment]
duno but wick is thinks it was made like 10hrs ago

**Comment by ghost** [comment]
Sorry for the confusion, English is not my native language and I thought you were talking about age. And how long do I have to wait for registration?

**Comment by RedMan13** [comment]
7 days

**Comment by ghost** [comment]
Okay, I'm using my old account :(

**Comment by ghost** [comment]
Thanks for the clarification!
