### ISSUE TITLE
Add "Scripts" blocks

### ISSUE THREAD

**Issue by ghost** [PenguinMod/PenguinMod-Vm#17]
This may be too complicated, but
This would make it easier to make programming languages on PenguinMod.
Scripts would be a extension with these
A button that creates a variable-like thing called a script. You can name the script.
add block (block) to [script v] // A block that adds a block to a script.
delete block (number) of [script v] // A block that deletes a block from a script
delete all blocks from [script v] // A block that deletes all blocks in a script.
insert (block) at (number) of [script v] // A block that would add a block at a certain spot in a script.
replace block (number) of [script v] with (block) // A block that would replace a block in a script with another.
run script [script v] // A block that would run a script.
DO NOT CONFUSE THIS WITH CODING A SCRIPT YOU CAN SEE. IT IS A INVISIBLE SCRIPT. YOU CANNOT PLACE HAT BLOCKS.
That's my suggestion. I wanted this for a while.

**Comment by Ianyourgod** [comment]
I feel like this is just making an extra layer of abstraction, and it doesn’t help with understanding how the language works because this is just something called transpiling. If you want help making programming languages please join the discord and I can try to teach you.

**Comment by ghost** [comment]
???

**Comment by JeremyGamer13** [comment]
what would the (block) input be? like what would you put inside

**Comment by ghost** [comment]
Blocks. Like "add block [block input] to [HiddenScript1]".

**Comment by JeremyGamer13** [comment]
so something like this?
![image](https://github.com/PenguinMod/PenguinMod-Vm/assets/69337718/1d436985-bded-4f01-baa1-31132c33affe)

**Comment by ghost** [comment]
Yup!

**Comment by JeremyGamer13** [comment]
seems like something i could try making

**Comment by SharkPool-SP** [comment]
> Yup!

We just reworked it and made it available to test in livetests:
https://studio.penguinmod.com/editor.html?livetests

If all is good we will release it publicly soon

**Comment by SharkPool-SP** [comment]
The extension is out!:
![image](https://github.com/PenguinMod/PenguinMod-Vm/assets/139097378/84064deb-d948-49ef-9938-81d6556c103a)
![image](https://github.com/PenguinMod/PenguinMod-Vm/assets/139097378/b8a268b8-1c8c-4ed7-a224-2691d075f46b)
Time to finally close this issue :)
