### ISSUE TITLE
Colored Variables & Lists

### ISSUE THREAD

**Issue by echoless3484** [PenguinMod/PenguinMod-Vm#20]
I have a suggestion for more customization in PenguinMod, seeing Colored Variables and Lists would be really cool to be able to sort things better

**Comment by Ianyourgod** [comment]
I think theres a tw extension for this, we're probably going to add all of them so yea

**Comment by echoless3484** [comment]
Is there really? 0_0

**Comment by Ianyourgod** [comment]
yeah. idk if its been added to the library but i saw the development in the tw dc

**Comment by JoshAtticus** [comment]
The extension is now available
