### ISSUE TITLE
CUSTOMIZABLE VARIABLES

### ISSUE THREAD

**Issue by GalacticCoderReturns** [PenguinMod/PenguinMod-Vm#21]
Don't confuse this with #20 
Hello! Got a new idea for PenguinMod that would be amazing.
You know variables, you cannot customize them. This would allow you to code the variable and even have custom textures!
For example:
when [gear v] of [my var v] clicked
change [my var v] by (1)

**Comment by RedMan13** [comment]
> Don't confuse this with #20 Hello! Got a new idea for PenguinMod that would be amazing. You know variables, you cannot customize them. This would allow you to code the variable and even have custom textures! For example: when [gear v] of [my var v] clicked change [my var v] by (1)

custom return blocks?

**Comment by JeremyGamer13** [comment]
i dont really understand how the clicked block would work, is it just when the variable is clicked on the stage?

**Comment by GalacticCoderReturns** [comment]
When a designed part of the variable is clicked.

**Comment by JeremyGamer13** [comment]
this seems like it would be possible, just really hard to add

**Comment by AndrewScripter587** [comment]
this is already a part of an existing extension by SharkPool. find their extension collection under the collections category when adding an extension, and you should get a new tab with a bunch of extensions. find the only one that is actually variable related(not the list one though) i forgot the name though.

**Comment by SharkPool-SP** [comment]
> Don't confuse this with #20 
> 
> Hello! Got a new idea for PenguinMod that would be amazing.
> 
> You know variables, you cannot customize them. This would allow you to code the variable and even have custom textures!
> 
> For example:
> 
> when [gear v] of [my var v] clicked
> 
> change [my var v] by (1)

You can use Variables Expanded from my gallery

**Comment by SharkPool-SP** [comment]
Update:
This can *actually* be done with one of my extensions: DOM Selector:
<img width="1324" alt="Screenshot 2024-07-17 at 12 11 57 AM" src="https://github.com/user-attachments/assets/60beb351-fef5-401c-92b3-65e672f40f78">

You just need a basic understanding of how query selectors and HTML work
