### ISSUE TITLE
Disable Compiler is nowhere

### ISSUE THREAD

**Issue by IceandFire04** [PenguinMod/PenguinMod-Vm#26]
### Expected Behavior

You should be able to see the disable compiler option in the advanced window.

### Actual Behavior

It's nowhere to be seen.

### Steps to Reproduce

Just check "Advanced" in the editor

### Operating System and Browser

Windows 11 Microsoft Edge (sorry)

**Comment by RedMan13** [comment]
this is an intentional change

**Comment by JeremyGamer13** [comment]
the compiler is required for certain blocks & extensions in PenguinMod, so the option isnt there to disable it
