### ISSUE TITLE
Boolean variables

### ISSUE THREAD

**Issue by EthanRStokes** [PenguinMod/PenguinMod-Vm#27]
Would be very convenient to have boolean variables instead of constantly using `if var = 1` or `var = true`

For modifying the state of these variables
Setting them to something that isn’t a Boolean just sets it to false (unless something else is preferred)

Examples of use:
`set <boolVar> to <true>`
`if <boolVar>`
`if <not<boolVar>>`

**Comment by JeremyGamer13** [comment]
cant you place variables into booleans already in pm

**Comment by EthanRStokes** [comment]
> cant you place variables into booleans already in pm

Yes but i mean boolean *exclusive* variables
Variables that can’t have numbers or text

**Comment by SharkPool-SP** [comment]
no. Its literally no difference. If you want it to be **exclusive** to true/false, **only** set it to **true or false**

**Comment by Ianyourgod** [comment]
im gonna close this, sp explained why.
