### ISSUE TITLE
Global functions

### ISSUE THREAD

**Issue by AndyMHo** [PenguinMod/PenguinMod-Vm#32]
Global functions would be nice to add, which are functions that can be spread across multiple sprites. The number of messages used in one of my projects is **immense** lol

![scratchypenguin](https://github.com/PenguinMod/PenguinMod-Vm/assets/125214805/68d07449-0311-4dec-8622-e83a69532177)

**Comment by AndyMHo** [comment]
With TurboBuilder being developed, I'm starting to reconsider this since you can just create an extension, which blocks can used across sprites.

**Comment by SharkPool-SP** [comment]
does this work for you:
![image](https://github.com/PenguinMod/PenguinMod-Vm/assets/139097378/07302ece-504e-457a-867d-a8ab9a9bcc45)

**Comment by SharkPool-SP** [comment]
The extension is out!:
![image](https://github.com/PenguinMod/PenguinMod-Vm/assets/139097378/84064deb-d948-49ef-9938-81d6556c103a)
![image](https://github.com/PenguinMod/PenguinMod-Vm/assets/139097378/b8a268b8-1c8c-4ed7-a224-2691d075f46b)
This is a viable workaround to global functions. If you want to close the issue then you can :)

**Comment by JeremyGamer13** [comment]
personally i think native global custom blocks is still a better solution, but its really hard/not possible to do that according to godslayerakp using the current system

**Comment by SharkPool-SP** [comment]
> personally i think native global custom blocks is still a better solution, but its really hard/not possible to do that according to godslayerakp using the current system

well this would be the best workaround for now as it does the tasks required

**Comment by AndyMHo** [comment]
for some reason i abandoned this but the Scripts extension is good enough for me, thanks!

**Comment by AndyMHo** [comment]
for some reason i abandoned this thread but the Scripts extension is good enough for me, thanks!

**Comment by AndyMHo** [comment]
...nnnnevermind. Blocks+ nor Scripts extension are not uploadable to penguinmod. any alternatives?

**Comment by SharkPool-SP** [comment]
> ...nnnnevermind. Blocks+ nor Scripts extension are not uploadable to penguinmod. any alternatives?

they are uploadable so long as you have a rank higher than newborn penguin

**Comment by AndyMHo** [comment]
oh, sorry for that
