### ISSUE TITLE
Blocks appear incorrectly on chromebook (was working before oct 30)

### ISSUE THREAD

**Issue by IceandFire04** [PenguinMod/PenguinMod-Vm#33]
### Expected Behavior

The blocks should appear correctly as they normally do

### Actual Behavior

They show up as red blocks saying "your mom" with a troll face emoji grabbed from discord cdn

### Steps to Reproduce

Load the editor on a chromebook

### Operating System and Browser

ChromeOS

**Comment by RedMan13** [comment]
change your name to anything but your mom :skull:

**Comment by IceandFire04** [comment]
bruh I made it when I was 7 and made an account here 💀 
also btw this hasn't changed either

**Comment by RedMan13** [comment]
> bruh I made it when I was 7 and made an account here 💀 also btw this hasn't changed either

your name in the editor isn't tied to your account 💀 
also you have to reload for the change to take effect :skull:

**Comment by IceandFire04** [comment]
didn't work :/

**Comment by RedMan13** [comment]
> didn't work :/
:skull:
[Screencast from 11-14-2023 03:49:27 AM.webm](https://github.com/PenguinMod/PenguinMod-Vm/assets/74981904/57318bb8-5f66-4f97-9e87-06d010e1ea9d)

**Comment by RedMan13** [comment]
bruh the recording doesnt show the mouse :skull:

**Comment by RedMan13** [comment]
i clicked on "reset" at the end there

**Comment by IceandFire04** [comment]
Omg I'm so sorry wasting your time :(
I had completely forgot about testing that
