### ISSUE TITLE
Penguinmod website down for 20+ days

### ISSUE THREAD

**Issue by hammouda101010** [PenguinMod/PenguinMod-Vm#50]
looks like penguinmod is too lazy to fix their website, altrough the editor works fine, witch is OK For me.

### Operating System and Browser

_every OS and browser_

**Comment by RedMan13** [comment]
read the website status 💀

**Comment by RedMan13** [comment]
the entire api is currently being rebuit **from the ground up** and the api is massive already without the extra account stuff being added to the new system so like, yeah

**Comment by derpygamer2142** [comment]
"too lazy" my ass

**Comment by hammouda101010** [comment]
> "too lazy" my ass

yeah, i was a dork for thinking this

**Comment by Ianyourgod** [comment]
yeah you were

**Comment by hammouda101010** [comment]
![6ad](https://github.com/PenguinMod/PenguinMod-Vm/assets/114447430/c86879f6-1f98-4117-8fed-f9dbdf78d8d6)

**Comment by derpygamer2142** [comment]
skill issue
