### ISSUE TITLE
package project button opens 2 tabs

### ISSUE THREAD

**Issue by AD1340** [PenguinMod/PenguinMod-Vm#51]
### Expected Behavior

opening 1 tab

### Actual Behavior

opens 2 tabs

### Steps to Reproduce

go to the editor, click file on the top left, and click package project

### Operating System and Browser

windows 11, microsoft edge

**Comment by AD1340** [comment]
does no one really wanna fix this.....

**Comment by RedMan13** [comment]
wiat what the fuck when did this issue exist

**Comment by Ianyourgod** [comment]
around 2 weeks ago i think!! hope this helps

**Comment by AD1340** [comment]
this was happening before I made the post I just made it now lol

**Comment by codingisfun2831t** [comment]
can confirm on windows 10. it seems to use a popup because it told me popup blocked and when I allowed, it open the two tabs.

**Comment by codingisfun2831t** [comment]
ow i checked the source and it seems like the open function is czlled twice (in https://github.com/PenguinMod/penguinmod.github.io/blob/develop/src/lib/tw-packager-integration-hoc.jsx)

**Comment by ilikecoding-197** [comment]
heres the pull request: https://github.com/PenguinMod/penguinmod.github.io/pull/65

**Comment by AD1340** [comment]
its been 2 months why hasnt anyone else tried to fix this yet 💀

**Comment by SharkPool-SP** [comment]
this was fixed a while ago lol
