### ISSUE TITLE
new block idea

### ISSUE THREAD

**Issue by AD1340** [PenguinMod/PenguinMod-Vm#52]
could you guys add in a block where its like the repeat until block but if the value is changed and the code is still in the middle of running it instantly stops

**Comment by SharkPool-SP** [comment]
I think you can already do that with other blocks

**Comment by AD1340** [comment]
oh do you know which one?

**Comment by SharkPool-SP** [comment]
On my gallery, Extra Controls, there's a step through blocks block

**Comment by JeremyGamer13** [comment]
could be added to controls expansion, mostly since its a bit too specific to be in the main control category

**Comment by AD1340** [comment]
thanks alot sharkpool!!! I needed this alot for my game....

**Comment by SharkPool-SP** [comment]
> could be added to controls expansion, mostly since its a bit too specific to be in the main control category

Erm Alr exists in my extension which is part of the main gallery :trollface:
