### ISSUE TITLE
be able to deload lists

### ISSUE THREAD

**Issue by AD1340** [PenguinMod/PenguinMod-Vm#53]
I think having more than 1k levels in a list is lagging my game....so could you guys please add a way to do this?
either way, it was still slight lag spiking with about 100 levels...

![image](https://github.com/PenguinMod/PenguinMod-Vm/assets/88950719/50557469-ab4a-4938-87f7-f97cc7886642)

**Comment by AD1340** [comment]
or could the lag spiking just be because it was open in the editor? either way this would still be really nice to have added in

**Comment by RedMan13** [comment]
just write better code
not our fault your storing so much data that the js array is having speed issues

**Comment by RedMan13** [comment]
> or could the lag spiking just be because it was open in the editor? either way this would still be really nice to have added in

yes, opening the editor always introduces a lag spike

**Comment by nmsderp** [comment]
maybe try loading levels from a static site so everything isn't just stuffed inside the project

**Comment by AD1340** [comment]
but the levels need to be saved locally, and its only supposed to be able to load from online when you play other peoples levels, and also I think the lag was only because it was open in the editor anyways because I didnt experience any slight lag when I played it from the project page, so im sorry for opening this stupid question lol, thanks for the suggestions

**Comment by AD1340** [comment]
but the levels need to be saved locally, and its only supposed to be able to load from online when you play other peoples levels, and also I think the lag was only because it was open in the editor anyways because I didnt experience any slight lag when I played it from the project page, so im sorry for opening this stupid question lol, thanks for the suggestions

**Comment by AD1340** [comment]
but the levels need to be saved locally, and its only supposed to be able to load from online when you play other peoples levels, and also I think the lag was only because it was open in the editor anyways because I didnt experience any slight lag when I played it from the project page, so im sorry for opening this stupid question lol, thanks for the suggestions

**Comment by RedMan13** [comment]
:bleh
