### ISSUE TITLE
delta time extension doesnt work properly on penguinmod

### ISSUE THREAD

**Issue by AD1340** [PenguinMod/PenguinMod-Vm#55]
### Expected Behavior

it should show the normal fps

### Actual Behavior

it keeps switching from 5000 fps to 10000 fps

### Steps to Reproduce

import this custom extension into penguinmod and show the fps variable
(https://extensions.turbowarp.org/XeroName/Deltatime.js)

### Operating System and Browser

windows 11, microsoft edge

**Comment by RedMan13** [comment]
that apears to be expected behavior

**Comment by RedMan13** [comment]
nvm but it is fixed now

**Comment by AD1340** [comment]
tank u
