### ISSUE TITLE
files extension from turbowarp open a file as block fills up whole screen instead of just the project frame

### ISSUE THREAD

**Issue by AD1340** [PenguinMod/PenguinMod-Vm#56]
### Expected Behavior

fill the project screen

### Actual Behavior

fills the whole editor page instead

### Steps to Reproduce

add a new extension and search up files and add it
run the "open a file as text" block

### Operating System and Browser

windows 11 microsoft edge

**Comment by RedMan13** [comment]
this is most definitely intended, as the files extension is meant to put the popup at the center of the page, not the center of the stage

**Comment by AD1340** [comment]
but it doesnt do that in normal turbowarp though

**Comment by RedMan13** [comment]
either way it most definitely is intended to be center of page on pm
