### ISSUE TITLE
Lag spikes in editor

### ISSUE THREAD

**Issue by AD1340** [PenguinMod/PenguinMod-Vm#59]
### Expected Behavior

It should run smooth

### Actual Behavior

slight lag spike every few seconds

### Steps to Reproduce

place 1 block down in the editor and move the code area around and look closely and compare it to how it runs on turbowarp.org

### Operating System and Browser

Windows 11, Microsoft Edge

**Comment by SharkPool-SP** [comment]
seems fine to me?

**Comment by JeremyGamer13** [comment]
do you have any browser extensions or other apps open while using the editor

**Comment by PuzzlingGGG** [comment]
yeah i agree with charkpole ive never gotten any lag from the editor. what are your specs? like cpu, gpu, etc

**Comment by SharkPool-SP** [comment]
The only time youd get a lag spike is by switching sprites/tabs. And maybe if your running a lot of code. Some more information/video showing this would be helpful

**Comment by RedMan13** [comment]
the editor makes sense to run the slowest since alot of what it does (or atleast is supposed to do) when running is checking debug information
~~also because blockly is piec-~~
it spiking is weirc tho... do you happen to be running on a device that has gardio (or something akin to it) installed?

**Comment by AD1340** [comment]
![tujytikrkejidtyuh](https://github.com/PenguinMod/PenguinMod-Vm/assets/88950719/f2b6cb9c-246a-4b50-bfec-9d42b5cb70a2)
these are my extensions

**Comment by AD1340** [comment]
[PuzzlingGGG](https://github.com/PuzzlingGGG) these are my specs
Processor	Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz   3.20 GHz
Installed RAM	8.00 GB (7.88 GB usable)
System type	64-bit operating system, x64-based processor

**Comment by AD1340** [comment]
nvm yeh extensions was the problem I think

**Comment by JeremyGamer13** [comment]
im probably gonna start suspecting web extensions more when it comes to lag, i already have a VR emulator chrome extension for testing things and it started lagging the editor constantly until i found it was the chrome extension
