### ISSUE TITLE
Dynamic menus not working in extension

### ISSUE THREAD

**Issue by chickencuber** [PenguinMod/PenguinMod-Vm#64]
### Expected Behavior

the block should appear and not have an error in the console

### Actual Behavior

the block doesn't show up and theres an error in the console

### Steps to Reproduce

1. load extension with dynamic menus with "Run extenstion without sandbox" set to true
2. it doesn't work

### Operating System and Browser

windows 11, google chrome
### code
this was made in an extension builder that I made, that I cant figure out how to fix, and as far as I can tell, its done in the same way as it says in the docs
```js
// Made with PenguinBuilder 3.2
// use PenguinBuilder at "https://chickencuber.github.io/PenguinBuilder/"
(function(Scratch) {
  const blocks = [];
  const vars = {};
  const menus = {};

  

  class Extension {
    getInfo() {
      return {
        "id": "dynamictest",
        "name": "dynamic menu test",
        "color1": "#0088ff",
        "blocks": blocks,
        "menus": menus,
      }
    }
  }
  
blocks.push({
  opcode: "dynamictest_Block_ID",
  blockType: Scratch.BlockType.COMMAND,
  text: "test[menu]",
  arguments: {
      "menu": {
           type: Scratch.ArgumentType.STRING,
           menu: "dynamictest_customMenu_menu",
  },

  },
  disableMonitor: false
});
Extension.prototype["dynamictest_Block_ID"] = function(args, util) {
  const localVars = {};
};


  menus["dynamictest_customMenu_dynamic_menu"] = {
    acceptReporters: true,
    items: "dynamictest_customMenu_dynamic_menu_func",
  };
  Extension.prototype["dynamictest_customMenu_dynamic_menu_func"] = function() {
    const localVars = {};
    return ['a', 'b', 'c'];
  };




  Scratch.extensions.register(new Extension());
})(Scratch);
```
the error it returns is `TypeError: Cannot read properties of undefined (reading 'acceptReporters') at Z._convertPlaceholders (https://studio.penguinmod.com/js/vendors~editor~embed~fullscreen~player~playground.60b3388e2adff9821c97.js:90:188988)`

**Comment by RedMan13** [comment]
blud you did not just

**Comment by RedMan13** [comment]
the ids don't match

**Comment by RedMan13** [comment]
also turbo builder issues are issues fr turbo builder, not us

**Comment by chickencuber** [comment]
It's not turbobuilder, it's penguinbuilder, and I made penguinbuilder, I couldn't figure out what was causing the issue

**Comment by chickencuber** [comment]
Also thanks, I see the issue now

**Comment by RedMan13** [comment]
> It's not turbobuilder, it's penguinbuilder, and I made penguinbuilder, I couldn't figure out what was causing the issue

point still stands, I thought Jeremy made penguin builder though
