### ISSUE TITLE
temporary variables turbowarp version bug

### ISSUE THREAD

**Issue by AD1340** [PenguinMod/PenguinMod-Vm#74]
delete all runtime variables block doesnt delete any variables, and when you click the checkbox on the active runtime variables reporter it doesnt show anything but when you click the block it does
![yes](https://github.com/user-attachments/assets/51d8aa15-21ed-4245-87fa-a510f7b21a18)

**Comment by AD1340** [comment]
getting error
TypeError: Cannot read properties of undefined (reading 'delete')
for delete runtime var block

and error
TypeError: Cannot read properties of undefined (reading 'has')
using runtime var exists?

im getting both these errors while trying to use these blocks in a custom block, pls fix ur stuff penguinmod 😭

**Comment by RedMan13** [comment]
tf

**Comment by RedMan13** [comment]
wait, do your variable names invlove periods

**Comment by AD1340** [comment]
oh well um erm its um its well its um complicated um maybe um yes

**Comment by RedMan13** [comment]
> oh well um erm its um its well its um complicated um maybe um yes

its still an issue with pm *but*, try turning on dangerous optimizations and seeing if the errors are still there, in pm the temp vars will try to explore the contents of an object based in the input keys instead of strictly returning the variable itself, dangerous optimizations turns this off for extra performance at the loss of a tiny but of simplicity

**Comment by AD1340** [comment]
wat do u mean by loss of tiny bit of simplicity

**Comment by AD1340** [comment]
![image](https://github.com/user-attachments/assets/4a072ab6-2538-4527-b153-b0402ba00d93)
dangerouz optimizations worked :D

**Comment by RedMan13** [comment]
> ![image](https://private-user-images.githubusercontent.com/88950719/377664638-4a072ab6-2538-4527-b153-b0402ba00d93.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyMTQyNTAsIm5iZiI6MTcyOTIxMzk1MCwicGF0aCI6Ii84ODk1MDcxOS8zNzc2NjQ2MzgtNGEwNzJhYjYtMjUzOC00NTI3LWIxNTMtYjA0MDJiYTAwZDkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE4VDAxMTIzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjMjFmYmE1MTFlMzE4YjYzY2VjMWQ1Y2M5NWQ2M2Q0ZDdkODg4NzllMzE2NWVkNTViMWUwMGEwY2JhYTlkYzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Uy_g8xApQnzSiplaMpGC4Y3H2SDbBLgfiNhG4IKH92s) dangerouz optimizations worked :D

yay!

**Comment by RedMan13** [comment]
> wat do u mean by loss of tiny bit of simplicity

as in instead of `get (baz) in (get (bar) in (get (foo) in (get (tempvar))))` you can just do `get (tempvar.foo.bar.baz)` (assuming tempvar contains `{"foo":{"bar":{"baz":"hellorld!"}}}`)
for this feature to work it is important that it is an obejct/map-like and not a json string that is inside the tempvar, a map-like would be something like the pm "objects" extension in the extension gallery

**Comment by RedMan13** [comment]
> > wat do u mean by loss of tiny bit of simplicity
> 
> as in instead of `get (baz) in (get (bar) in (get (foo) in (get (tempvar))))` you can just do `get (tempvar.foo.bar.baz)` (assuming tempvar contains `{"foo":{"bar":{"baz":"hellorld!"}}}`) for this feature to work it is important that it is an obejct/map-like and not a json string that is inside the tempvar, a map-like would be something like the pm "objects" extension in the extension gallery

**Comment by AD1340** [comment]
why is it closed when the main issue from the original comment is still present

**Comment by AD1340** [comment]
@RedMan13 REDMANNNNNN!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! REOPEN ITTTTTTTTTTTTTTTT!!!!!!!!!!

**Comment by RedMan13** [comment]
> why is it closed when the main issue from the original comment is still present

which one

**Comment by RedMan13** [comment]
ehh both need fixed anyways

**Comment by AD1340** [comment]
lol

**Comment by RedMan13** [comment]
so, tf ?
what on skidi was making the second set of errors

also fixed the bug this thread was orignally for

**Comment by AD1340** [comment]
NOOOOOOOOOOO!!!!!!!!!! WAAAAAAAAAAAIIIIIIIIITTTTTTTTT!!!!!!! THERES ONE LAST BUGGGGGGGGGGGGGG!!!!!!!!!
![AGADGAGADNHSAG](https://github.com/user-attachments/assets/eebc382a-3fb2-4887-ad54-fbe2201f63df)

**Comment by JeremyGamer13** [comment]
@RedMan13

**Comment by RedMan13** [comment]
what on shit

**Comment by RedMan13** [comment]
oh wait do monitors never try to read the compield version

**Comment by RedMan13** [comment]
i believe that is the case, so this should now be fied
