### ISSUE TITLE
In-project file storage for extensions

### ISSUE THREAD

**Issue by electricprogramming** [PenguinMod/PenguinMod-Vm#75]
I am trying to write an extension involving data management, and make it as similar as possible to the built-in variable and list sections. I am mainly making it for TurboWarp, but i want to support PenguinMod too if possible. However, in order to do so, I have to use buttons, `prompt()`, and be able to *STORE DATA IN THE PROJECT ARCHIVE*. This has been implemented in TurboWarp via
```js
vm.runtime.extensionStorage[extensionId]
```
but it doesn't seem to exist in PenguinMod...

*OTHER THAN THE FACT THAT* if you open the `project.json` file out of a project archive of a project that uses the `jgExtendedAudio` extension, it says something like
```json
"extensionData": {
    "jgExtendedAudio": [
      {
        "id": "audio",
        "sources": {},
        "globalVolume": 1,
        "globalSpeed": 1,
        "globalPitch": 0,
        "globalPan": 0
      },
      {
        "id": "audio group 2",
        "sources": {},
        "globalVolume": 1,
        "globalSpeed": 1,
        "globalPitch": 0,
        "globalPan": 0
      }
    ]
  }
```
which means that there probably is some way. So then I go to the source of the `jgExtendedAudio` extension in the extensions directory and there is **NOTHING** I can find that hints at saving data. 

So if it is implemented please tell me how to use it, and otherwise, please implement it...
Thanks!

**Comment by SharkPool-SP** [comment]
```js
    serialize() {
      return { extensionID: { data } }
    }
    deserialize(data) {
      if (data.extensionID !== undefined) {
      // export data
        }
      }
    }
```

**Comment by electricprogramming** [comment]
Does this also work in TurboWarp?

**Comment by SharkPool-SP** [comment]
> Does this also work in TurboWarp?

no

**Comment by electricprogramming** [comment]
> > Does this also work in TurboWarp?
> 
> no

then how do i make it support both

**Comment by SharkPool-SP** [comment]
use both, check if its penguinmod or not

**Comment by electricprogramming** [comment]
using
```js
(function(Scratch) {
  if (Scratch.extensions.isPenguinMod) {
    // create class and register pm version...
  } else {
    // create class and register tw version...
  }
})();
```
?

**Comment by RedMan13** [comment]
> > > Does this also work in TurboWarp?
> > 
> > 
> > no
> 
> then how do i make it support both

implement both

no need to check what the extension is running on since the two systems are vastly different

**Comment by SharkPool-SP** [comment]
> > > > Does this also work in TurboWarp?
> 
> > > 
> 
> > > 
> 
> > > no
> 
> > 
> 
> > then how do i make it support both
> 
> 
> 
> implement both
> 
> 
> 
> no need to check what the extension is running on since the two systems are vastly different 

Actually you *do* need to check, mainly for importing data

**Comment by RedMan13** [comment]
> > > > > Does this also work in TurboWarp?
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > no
> > 
> > 
> > > 
> > 
> > 
> > > then how do i make it support both
> > 
> > 
> > implement both
> > no need to check what the extension is running on since the two systems are vastly different
> 
> Actually you _do_ need to check, mainly for importing data

thats literally blatantly false?

**Comment by RedMan13** [comment]
just initialize the turbowarp variable if it doesnt exist and then store into that when pm tells you to losd in new save data

**Comment by SharkPool-SP** [comment]
Nuh uh

**Comment by RedMan13** [comment]
```js
vm.runtime.extensionStorage ??= {};
...
serialize() { return vm.runtime.extensionStorage[extensionID] }
deserislize(dat) { vm.runtime.extensionStorage[extensionID] = dat }
```
