### ISSUE TITLE
Suggestion: dropdown menus in custom blocks

### ISSUE THREAD

**Issue by AD1340** [PenguinMod/PenguinMod-Vm#76]
pls like how u can do with broadcast blocks
![block_10_17_2024-8_31_27 PM](https://github.com/user-attachments/assets/159446a7-f9d7-4578-af66-ec3d3b247423)

**Comment by RedMan13** [comment]
this was added alresdy i thought?
either way its been suggested millions of times and if it isnt gere already it will be in the future
