### ISSUE TITLE
cst's 3d extension doesnt do anything when i try to import it :(

### ISSUE THREAD

**Issue by AD1340** [PenguinMod/PenguinMod-Vm#77]
https://raw.githubusercontent.com/CST1229/turbowarp-extensions/3d/extensions/CST1229/3d.js

**Comment by SharkPool-SP** [comment]
because its using a turbowarp-only api. Complain to CST

**Comment by AD1340** [comment]
they cant add the turbowarp only api? :c

**Comment by RedMan13** [comment]
> because its using a turbowarp-only api. Complain to CST

whar api?
