### ISSUE TITLE
Suggestion: make letters from block in operators need the same amount of characters as when u get its length

### ISSUE THREAD

**Issue by AD1340** [PenguinMod/PenguinMod-Vm#85]
sorry for making an issue about the tiniest thing but can u guys pls make it so i dont need to add 1 more extra character than the actual length (i suck at explaining things)
![image](https://github.com/user-attachments/assets/4ad2f6a4-eced-44e0-8e3d-258aaab346c3)
![image](https://github.com/user-attachments/assets/07251c53-58d6-4847-b7dc-7cd4785d0cb6)

**Comment by PuzzlingGGG** [comment]
that's js for you just add one this exists for every scratch mod

**Comment by jwklong** [comment]
i would like to point out theres no letter zero so,,,

**Comment by RedMan13** [comment]
yeah, we arnt supposed to just change the fundamental functionality of a block just cause

**Comment by AD1340** [comment]
kk

**Comment by the-can-of-soup** [comment]
In JavaScript and a lot of other programming languages, ranges are in the form [m, n), which means that it includes the first number, but only includes all of the characters _up until_ the second number. The block behaves like this so that it is consistent with other programming languages.

However, in many other programming languages, indexes are "0-based" instead of "1-based", meaning that the first letter would be 0, and then the second would be 1, and so on, instead of 1, 2, etc. This block follows the [m, n) standard from JS, but it fails to follow the 0-based standard. I think it should fully follow JS standards, or fully follow Scratch standards; not something in between. But that's just my bad opinion.

**Comment by JeremyGamer13** [comment]
it's a mistake that was done when implementing the block, it would be ideal to change it now but i believe there are too many uses of this block already in existing projects for it to be fixable
its possible i can just make a new block to replace it but i havent done that yet

**Comment by SharkPool-SP** [comment]
> it's a mistake that was done when implementing the block, it would be ideal to change it now but i believe there are too many uses of this block already in existing projects for it to be fixable its possible i can just make a new block to replace it but i havent done that yet

Why not duplicate the block and hide the existing one

**Comment by Ianyourgod** [comment]
this is a quirk of java then sucked into javascript. i think it’s fine

**Comment by RedMan13** [comment]
> this is a quirk of java then sucked into javascript. i think it’s fine

0-strlen works in js, it doesnt in pm because whe it was added it was added with sub one on both sides

**Comment by Ianyourgod** [comment]
> > this is a quirk of java then sucked into javascript. i think it’s fine
> 
> 0-strlen works in js, it doesnt in pm because whe it was added it was added with sub one on both sides

bad code moment

**Comment by AD1340** [comment]
> In JavaScript and a lot of other programming languages, ranges are in the form [m, n), which means that it includes the first number, but only includes all of the characters _up until_ the second number. The block behaves like this so that it is consistent with other programming languages.
> 
> However, in many other programming languages, indexes are "0-based" instead of "1-based", meaning that the first letter would be 0, and then the second would be 1, and so on, instead of 1, 2, etc. This block follows the [m, n) standard from JS, but it fails to follow the 0-based standard. I think it should fully follow JS standards, or fully follow Scratch standards; not something in between. But that's just my bad opinion.

Bro wrote a whole essay 💀
