### ISSUE TITLE
when you view a project with custom settings like widescreen, when you view another project from that same page it doesnt return back to normal

### ISSUE THREAD

**Issue by AD1340** [PenguinMod/PenguinMod-Vm#86]
https://github.com/user-attachments/assets/2c677c1d-3b3b-422c-a238-a9f5d07d1993

**Comment by AD1340** [comment]
i think this has to do with no new settings being stored in the different project

**Comment by RedMan13** [comment]
yes
the entirety of scratch is designed horribly for doing this, you should always reload when doing things like changing project saves. especially since things like extensions and the runtine itself can have states that shouldve been cleared and didnt on the next save load and so causes errors with the project itself

**Comment by AD1340** [comment]
:c

**Comment by AD1340** [comment]
can u guys make it reload the whole page instead then

**Comment by RedMan13** [comment]
no cause the save you passed in to he loaded wouldnt then continue to exit when the page reloada 🥱

**Comment by AD1340** [comment]
i meant can u guys make it load a new page entirely when u click on a project down there instead of loading the new project onto the existing page

> no cause the save you passed in to he loaded wouldnt then continue to exit when the page reloada 🥱

**Comment by RedMan13** [comment]
blud its the same damn issue either way, the answer is still no we can not

**Comment by AD1340** [comment]
> blud its the same damn issue either way, the answer is still no we can not

dude how turbowarp when u click a project down there right now it loads a whole new page i meant to make it do that

**Comment by RedMan13** [comment]
it already does that

**Comment by AD1340** [comment]
it clearly doesnt what

**Comment by AD1340** [comment]
https://github.com/user-attachments/assets/7ed00cda-01f8-4c01-aed7-3eb3a3096a66

look, the turbowarp one loads a new page entirely while the penguinmod one doesnt look at the loading icon at the tab

**Comment by AD1340** [comment]
https://github.com/user-attachments/assets/8f4f60af-5612-431c-8ed2-f9ce964d83d3

**Comment by AD1340** [comment]
red man u dum dum
