### ISSUE TITLE
username block stopped working even while logged in

### ISSUE THREAD

**Issue by AD1340** [PenguinMod/PenguinMod-Vm#87]
![Capture](https://github.com/user-attachments/assets/276ede46-0d2e-49ce-8c1c-430b44b3ba17)

**Comment by Ianyourgod** [comment]
yeah jeremy made it not work because the solution we had before used a shit ton of network usage

**Comment by AD1340** [comment]
pls maek it work again pls pls  p l s

**Comment by the-can-of-soup** [comment]
This is just a server issue (they are still working on fixing it; check [https://status.penguinmod.com/](url))

**Comment by Ianyourgod** [comment]
> This is just a server issue (they are still working on fixing it; check [https://status.penguinmod.com/](url))

Read the above messages. I am the server developer. You are wrong.

**Comment by AD1340** [comment]
cooked

**Comment by AD1340** [comment]
its patchy watchy
