### ISSUE TITLE
TypeError: Failed to fetch while trying to load a project

### ISSUE THREAD

**Issue by AD1340** [PenguinMod/PenguinMod-Vm#89]
![image](https://github.com/user-attachments/assets/35c96ca9-fe9d-4415-a4a1-b1e5f932b050)

**Comment by AD1340** [comment]
ill send the project file in a few hours i was trying to load my game at school

**Comment by the-can-of-soup** [comment]
OK I think It's a project issue.

**Comment by AD1340** [comment]
it seems it has to do with the wifi as it loads on vpn

**Comment by AD1340** [comment]
it has to do with the school wifi it loaded on vpn
